#---------------------------------------------------------------------------------------------------
#general
swagger: "2.0"
info:
  title: "Integration Architecture"
  description: "This API shows all our endpoints. By clicking on an endpoint you will get a detailed
    description and the possibility to try out if and how the endpoints work."
  version: 1.0.0
host:
  localhost:8080
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

#---------------------------------------------------------------------------------------------------
#endpoint description
paths:
  /auth:
    #authenticate
    post:
      tags:
        - Authentication
      operationId: postAuthentication
      summary: authenticate the user
      description: This method authenticates a user.
      deprecated: false
      parameters:
        - in: formData
          type: string
          name: name
        - in: formData
          type: string
          name: password
      responses:
        200:
          description: "Success"
    get:
      tags:
        - Authentication
      operationId: getAuthentication
      summary: checks if user is authenticated
      description: This method checks if a user is authenticated.
      deprecated: false
      responses:
        200:
          description: "Success"
    delete:
      tags:
        - Authentication
      operationId: deleteAuthentication
      summary: deauthenticates a user
      description: This method deauthenticates a user.
      deprecated: false
      responses:
        200:
          description: "Success"
  /user:
    post:
      tags:
        - User
      operationId: postUser
      summary: create a new user
      description: This method creates a new user.
      deprecated: false
      parameters:
        - in: body
          name: user
          description: the new user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: "Success"
    get:
      tags:
        - User
      operationId: getUser
      summary: gets all user
      description: This method returns all user.
      deprecated: false
      responses:
        200:
          description: the requested users
          schema:
            $ref: '#/definitions/User'
    put:
      tags:
        - User
      operationId: updateUser
      summary: updates a user
      description: This method updates a user.
      deprecated: false
      parameters:
        - in: body
          name: user
          description: the new user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: "Success"
  /user/:username:
    get:
      tags:
        - User
      operationId: getOneUser
      summary: gets one user
      description: This method returns one user.
      deprecated: false
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        200:
          description: the requested users
          schema:
            $ref: '#/definitions/User'
    delete:
      tags:
        - User
      operationId: deleteUser
      summary: delets one user
      description: This method deletes one user.
      deprecated: false
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        200:
          description: "Success"
  /username/:username/pw:
    put:
      tags:
        - User
      operationId: updateUserPw
      summary: updates a users password
      description: This method updates a users password.
      deprecated: false
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: body
          name: userpasswords
          description: the old and new password
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: "Success"
  /settings:
    put:
      tags:
        - Settings
      operationId: updateSetting
      summary: updates a setting
      description: This method updates a setting.
      deprecated: false
      parameters:
        - in: body
          name: userpasswords
          description: the old and new password
          schema:
            $ref: '#/definitions/Setting'
      responses:
        200:
          description: "Success"
  /settings/:name:
    get:
      tags:
        - Settings
      operationId: getSetting
      summary: gets a setting
      description: This method gets a setting.
      deprecated: false
      parameters:
        - in: path
          name: name
          required: true
          type: string
      responses:
        200:
          description: "Success"
  /salesman:
    get:
      tags:
        - Salesman
      operationId: getSalesmen
      summary: gets all salesmen
      description: This method gets all salesmen.
      deprecated: false
      responses:
        200:
          description: the requested salesmen
          schema:
            $ref: '#/definitions/Salesman'
  /salesman/:id:
    get:
      tags:
        - Salesman
      operationId: getOneSalesman
      summary: get one salesman
      description: This method gets one salesman.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: number
      responses:
        200:
          description: the requested salesman
          schema:
            $ref: '#/definitions/Salesman'
  /salesman/:id/bonus/:year/refresh_review:
    get:
      tags:
        - Salesman
      operationId: getNewReview
      summary: refresh review
      description: This method refreshes the review.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
      responses:
        200:
          description: 'Success'
  /salesman/:id/bonus/:year/get_review:
    get:
      tags:
        - Salesman
      operationId: getReview
      summary: get review
      description: This method gets the review.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
      responses:
        200:
          description: 'Success'
  /salesman/:id/bonus/get_years:
    get:
      tags:
        - Salesman
      operationId: getYears
      summary: get the years where orders exist
      description: This method gets the years where oreders for a salesman exist.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: 'Success'
  /salesman/:id/bonus/:year/set_remarks:
    post:
      tags:
        - Salesman
      operationId: postRemark
      summary: creates a remark for a review
      description: This method creates a remark for a review.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
        - in: formData
          name: remark
          type: string
      responses:
        200:
          description: 'Success'
  /salesman/:id/bonus/:year/approve_bonus:
    post:
      tags:
        - Salesman
      operationId: postApprove
      summary: approves a review
      description: This method approves a review.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
      responses:
        200:
          description: 'Success'
  /salesman/:id/evaluationrecord:
    post:
      tags:
        - EvaluationRecord
      operationId: postRecord
      summary: creates a record
      description: This method creates a record.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - $ref: '#/parameters/evaluationrecord'
      responses:
        200:
          description: 'Success'
    get:
      tags:
        - EvaluationRecord
      operationId: getRecords
      summary: gets all records
      description: This method gets all records.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: the requested records
          schema:
            $ref: '#/definitions/EvaluationRecord'
  /salesman/:id/evaluationrecord/:year:
    get:
      tags:
        - EvaluationRecord
      operationId: getOneRecord
      summary: gets one records
      description: This method gets one record.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
      responses:
        200:
          description: the requested record
          schema:
            $ref: '#/definitions/EvaluationRecord'
    delete:
      tags:
        - EvaluationRecord
      operationId: deleteRecord
      summary: deletes one records
      description: This method deletes one record.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
      responses:
        200:
          description: 'Success'
  /salesman/:id/evaluationrecord/:year/entry:
    post:
      tags:
        - EvaluationRecordEntry
      operationId: createEntry
      summary: creates a entry
      description: This method creates an entry.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
        - $ref: '#/parameters/evaluationrecordentry'
      responses:
        200:
          description: 'Success'
    get:
      tags:
        - EvaluationRecordEntry
      operationId: getAllEntry
      summary: gets all entries
      description: This method gets all entries.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
      responses:
        200:
          description: the requested entries
          schema:
            $ref: '#/definitions/EvaluationRecordEntry'
    put:
      tags:
        - EvaluationRecordEntry
      operationId: updateEntry
      summary: update entry
      description: This method updates an entry.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
        - $ref: '#/parameters/evaluationrecordentry'
      responses:
        200:
          description: 'Success'
  /salesman/:id/evaluationrecord/:year/entry/:name:
    get:
      tags:
        - EvaluationRecordEntry
      operationId: getOneEntry
      summary: get one entry
      description: This method updates an entry.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
        - in: path
          name: name
          type: string
          required: true
      responses:
        200:
          description: the requested entry
          schema:
            $ref: '#/definitions/EvaluationRecordEntry'
    delete:
      tags:
        - EvaluationRecordEntry
      operationId: deleteEntry
      summary: delete an entry
      description: This method deletes an entry.
      deprecated: false
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: year
          required: true
          type: string
        - in: path
          name: name
          type: string
          required: true
      responses:
        200:
          description: 'Success'

----------------------------------------------------------------
#model descriptions
definitions:
  #Setting
  Setting:
    type: object
    properties:
      name:
        type: string
      value:
        type: number
    required:
      - name
      - value
  #Salesman definition
  Salesman:
    type: object
    properties:
      id:
        type: integer
      firstname:
        type: string
      lastname:
        type: string
    required:
      - id
      - firstname
      - lastname
  #EvaluationRecord definition
  EvaluationRecord:
    type: object
    properties:
      _id:
        type: string
      id:
        type: integer
      EvaluationRecord:
        type: object
        properties:
          year:
            type: integer
          entries:
            type: array
            items:
              $ref: '#/definitions/EvaluationRecordEntry'
        required:
          - year
    required:
      - id
  #EvaluationRecordEntry definition
  EvaluationRecordEntry:
    type: object
    properties:
      target:
        type: integer
      actual:
        type: integer
      name:
        type: string
    required:
      - target
      - actual
      - name
  #User definition
  User:
    type: object
    properties:
      displayname:
        type: string
      username:
        type: string
      password:
        type: string
      group:
        type: number
      employeeId:
        type: number
    required:
      - displayname
      - username
      - password
      - group
#---------------------------------------------------------------------------------------------------
#parameter descriptions
parameters:
  #body parameter
  evaluationrecord:
    name: EvaluationRecord
    in: body
    description: The EvaluationRecord that you want to post
    required: true
    schema:
      properties:
        year:
          type: integer
        entries:
          type: array
          items:
            $ref: '#/definitions/EvaluationRecordEntry'
      required:
        - year
  evaluationrecordentry:
    name: EvaluationRecordEntry
    in: body
    description: The EvaluationRecordEntry that you want to post/put
    required: true
    schema:
      $ref: '#/definitions/EvaluationRecordEntry'
